name: Autograding

on: [push]

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install numpy
        pip install torch

    - name: Run pytest
      run: |
        pytest
